
version: '3'
services:
  rasptank_developer:
    image: humble-rasptank:latest
    container_name: rasptank_developer
    privileged: true
    user: rasptank
    working_dir: /home/rasptank
    volumes:
      - /dev:/dev
      - /home/daiego/rasptank_control:/home/rasptank/rasptank_control
    command: ["tail", "-f", "/dev/null"]
    network_mode: host
    restart: always